/* currentTime.h
   Generated by wsdl2h 2.8.21 from currentTime.wsdl and typemap.dat
   2015-03-10 08:35:29 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2014 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on currentTime.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   urn:currentTime                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:currentTime"

*/

#define SOAP_NAMESPACE_OF_ns1	"urn:currentTime"
//gsoap ns1   schema namespace:	urn:currentTime
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class _ns1__currentTime.
class _ns1__currentTime;

//  Forward declaration of class _ns1__currentTimeResponse.
class _ns1__currentTimeResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:currentTime                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:currentTime                                                          *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "urn:currentTime":currentTime
/// @brief "urn:currentTime":currentTime is a complexType.
///
/// class _ns1__currentTime operations:
/// - soap_new__ns1__currentTime(soap*) allocate
/// - soap_new__ns1__currentTime(soap*, int num) allocate array
/// - soap_new_req__ns1__currentTime(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__currentTime(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__currentTime(soap*, _ns1__currentTime*) deserialize from a stream
/// - int soap_write__ns1__currentTime(soap, _ns1__currentTime*) serialize to a stream
class _ns1__currentTime
{ public:
/// Element "a" of XSD type xs:double.
    double                               a                              1;	///< Required element.
/// Element "b" of XSD type xs:double.
    double                               b                              1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "urn:currentTime":currentTimeResponse
/// @brief "urn:currentTime":currentTimeResponse is a complexType.
///
/// class _ns1__currentTimeResponse operations:
/// - soap_new__ns1__currentTimeResponse(soap*) allocate
/// - soap_new__ns1__currentTimeResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__currentTimeResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__currentTimeResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__currentTimeResponse(soap*, _ns1__currentTimeResponse*) deserialize from a stream
/// - int soap_write__ns1__currentTimeResponse(soap, _ns1__currentTimeResponse*) serialize to a stream
class _ns1__currentTimeResponse
{ public:
/// Element "result" of XSD type xs:double.
    double                               result                         1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:currentTime                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:currentTime                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	currentTime 
//gsoap ns1  service type:	currentTimePortType 
//gsoap ns1  service port:	http://www.yourdomain.com/currentTime.cgi 
//gsoap ns1  service namespace:	urn:currentTime 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage currentTime Definitions

@section currentTime_bindings Service Bindings

  - @ref currentTime

@section currentTime_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page currentTime Binding "currentTime"

@section currentTime_service Service Documentation "currentTime"
gSOAP 2.8.21 generated service definition

@section currentTime_operations Operations of Binding "currentTime"

  - @ref __ns1__currentTime

@section currentTime_ports Endpoints of Binding "currentTime"

  - http://www.yourdomain.com/currentTime.cgi

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   currentTime                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__currentTime                                                       *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__currentTime" of service binding "currentTime".
Service definition of function ns__currentTime

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__currentTime(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__currentTime*                  ns1__currentTime,
    // output parameters:
    _ns1__currentTimeResponse          &ns1__currentTimeResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__currentTime(
    struct soap *soap,
    // input parameters:
    _ns1__currentTime*                  ns1__currentTime,
    // output parameters:
    _ns1__currentTimeResponse          &ns1__currentTimeResponse
  );
@endcode

C++ proxy class (defined in soapcurrentTimeProxy.h):
@code
  class currentTimeProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapcurrentTimeService.h):
@code
  class currentTimeService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	currentTime SOAP
//gsoap ns1  service method-style:	currentTime document
//gsoap ns1  service method-encoding:	currentTime literal
//gsoap ns1  service method-action:	currentTime ""
//gsoap ns1  service method-output-action:	currentTime Response
int __ns1__currentTime(
    _ns1__currentTime*                  ns1__currentTime,	///< Input parameter
    _ns1__currentTimeResponse          &ns1__currentTimeResponse	///< Output parameter
);

/**

@page currentTime Binding "currentTime"

@section currentTime_policy_enablers Policy Enablers of Binding "currentTime"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "urn:currentTime"

  - <currentTime> @ref _ns1__currentTime
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__currentTime(struct soap*, _ns1__currentTime*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__currentTime(struct soap*, _ns1__currentTime*);
    @endcode

  - <currentTimeResponse> @ref _ns1__currentTimeResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__currentTimeResponse(struct soap*, _ns1__currentTimeResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__currentTimeResponse(struct soap*, _ns1__currentTimeResponse*);
    @endcode

*/

/* End of currentTime.h */
