#ifndef CONEXIONCLIENTE_GLOBAL_H
#define CONEXIONCLIENTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONEXIONCLIENTE_LIBRARY)
#  define CONEXIONCLIENTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONEXIONCLIENTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONEXIONCLIENTE_GLOBAL_H
